### ISSUE TITLE
Usability improvements 

### ISSUE THREAD

**Issue by NullNomad** [cgebe/burstcoin-wallet#6]
Please find some suggestions on usability improvements which would drastically increase user satisfaction.
  1. Balance Tab - Bigger barcode, around 40 to 50% of the screen.
  2.  History Tab - Remove the IN/OUT and use up/down arrows with green/red colors. This will declutter the 
                             area or move that up/down arrows next to BURST movements.
  3. Accounts: Display name of the accounts if it's imported or ability to name an account.
                      Currently, we display account and Numeric Account ID and it should be great to have easy to read name
4) Send Tab - Remove the center Burst Logo because we display BURST logo two times in this tab
If we could show below information it would be much more usable,

> 
> Current wallet name/number  and balance in BURST/USD
> To BURST Account number/ Scan barcode
> Number of burst and fees  = Rounded to two decimal USD

5) Double tap to copy BURST address in any place in the application.
 This would allow copying my address by double tapping and share in any mediums.

![screenshot_20170912-020246](https://user-images.githubusercontent.com/2860620/30310992-4c0956ea-9761-11e7-9db2-59b6025e9105.png)

![screenshot_20170912-022312](https://user-images.githubusercontent.com/2860620/30311023-6d4214c8-9761-11e7-8c1d-d76a738a77bc.png)

**Comment by cgebe** [comment]
I let this open for discussion.

**Comment by rico666** [comment]
1st I would vote to declutter these - partially unrelated things - in separate issues.
Improves the usability of the feedback a lot. :-)

But now that we have them here - let's discuss en bulk.

1) I agree on the bigger barcode. Don't overdo it, but use the white space more.

2) I also agree that incoming payments should be marked green, outgoing red.
(the amount) Doing so, allows you to omit any arrows. ANd the status (in progress/unconfirmed, confirmed) you do with the checkmark etc. can be directly behind the "BURST".
While we are at it, please ditch the AM/PM time format and use 24h (or what the OS is set to)

3) no opinion

4) agree

5) agree that we need a way to copy. Not sure if double tap (instead of holding) is the standard. Leave that to you.

**Comment by NullNomad** [comment]
> 1st I would vote to declutter these - partially unrelated things - in separate issues.
> Improves the usability of the feedback a lot. :-) 

lol, Next time it will be decluttered and sit in its own issue!!

5) Any way is fine, double tap or copy to clipboard button also fine!!!
